<?php

namespace AppBundle\Repository;
use Symfony\Component\HttpFoundation\Response;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends \Doctrine\ORM\EntityRepository
{
    public function isGranted($token)
    {
        //improvising a provisory "security" sistem :D
        if($token !== '34342532243') {
            return null;
        }
        return Response::HTTP_OK;
    }

}
