calendar_api_add:
    path:  /add/{date}
    defaults: { _controller: AppBundle:Api/Actions:add, _format: json }
    requirements:
    method: ["POST"]

calendar_api_select:
    path:  /selectAll
    defaults: { _controller: AppBundle:Api\Actions:select, _format: json }
    requirements:
    method: ["GET"]

calendar_api_select_event:
    path:  /select_event/{id}
    defaults: { _controller: AppBundle:Api\Actions:selectOne, _format: json }
    requirements:
    method: ["GET"]

calendar_api_update_single:
    path:  /updateEvent/{id}
    defaults: { _controller: AppBundle:Api\Actions:updateHourEvent, _format: json }
    requirements:
    method: ["PATCH"]

calendar_api_update_full:
    path:  /update/{id}
    defaults: { _controller: AppBundle:Api\Actions:updateEvent, _format: json }
    requirements:
    method: ["PUT"]

calendar_api_delete:
    path:  /delete/{id}
    defaults: { _controller: AppBundle:Api\Actions:delete, _format: json }
    requirements:
    method: ["DELETE"]

